
#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define SCREEN_WIDTH 160
#define SCREEN_HEIGHT 144

#define SCREEN_SCALE 5

#define WINDOW_WIDTH (SCREEN_WIDTH * SCREEN_SCALE)
#define WINDOW_HEIGHT (SCREEN_HEIGHT * SCREEN_SCALE)

#endif